### ISSUE TITLE
Can't connect the website to download the pretrained model.

### ISSUE THREAD

**Issue by vincentgc** [shoutOutYangJie/Few-Shot-Adversarial-Learning-for-face-swap#1]
Hi, I can't connect the "http://www.robots.ox.ac.uk/~albanie/pytorch-models.html" so the pretrained model is unavailable.  Are there other ways to share the pretrained model?

**Comment by shoutOutYangJie** [comment]
I can connect  the website . Because some copyrights,  I can't public this weight model. sorry
